select name from customer;
select name,city from customer;
select * from product;
select * from customer where city = 'Chennai';
select * from customer where cus_no = '1001';
select * from product where descr in ('XXX','YYY');
select * from product where unit_price > 2000;
select * from customer where city in ('Chennai','Bangalore','Hyderabad');
select * from product where unit_price > 1000 and unit_price <= 5000;
update product set unit_price = unit_price + 100 where prod_no = '1001';
delete from customer where cus_no = '1005';
update customer set address1 = '25, Ninth Street' where cus_no = '1001';
select * from customer where city = 'Chennai' and name like 'S%';
select * from customer where name like '_a%';
select name from customer order by name asc;
select count(Prod_no) from product;
select avg(unit_price) from product;
select max(unit_price) from product;
select min(unit_price) from product;
select count(prod_no) from product where unit_price > 2000;