select order_no, del_date-order_date as days from orders;
select order_date + interval '1 month' as one_month_from_order from orders;
select date_part('month', del_date) as delivery_month from orders;
select upper(name) from customer;
select rpad(descr, 25) from product;
select substring(name from 1 for 3) from customer;
select max(length(name)) from customer;
select to_char(del_date, 'DD Month YYYY') from orders;
update customer set name = regexp_replace(name, 'e', 'a') where name like '%e%';
select to_char(order_date, 'Day') from orders;
select upper(substring(name from 1 for 1)) from customer;
select substring(name from 2 for 5) from customer;
select current_date;
select sum(unit_price) from orders, product where orders.order_status = 'fulfilled';
select count(distinct(product_no)) from sales_order_details;