select Name from Customer;
select Name,City from Customer;
select * from Product;
select * from Customer where City = 'Chennai';
select * from Customer where Cus_no = '1001';
select * from Product where Descr in ('XXX','YYY');
select * from Product where Unit_price > 2000;
select * from Customer where City in ('Chennai','Bangalore','Hyderabad');
select * from Product where Unit_price > 1000 and Unit_price <= 5000;
update Product set Unit_price = Unit_price + 100 where Prod_no = '1001';
delete from Customer where Cus_no = '1005';
update Customer set Address1 = '25, Ninth Street' where Cus_no = '1001';
select * from Customer where City = 'Chennai' and Name like 'S%';
select * from Customer where Name like '_a%';
select Name from Customer order by Name asc;
select count(Prod_no) from Product;
select avg(Unit_price) from Product;
select max(Unit_price) from Product;
select min(Unit_price) from Product;
select count(Prod_no) from Product where Unit_price > 2000;